cloud9:
  command: "--listen 0.0.0.0 -p 8080 -w /workspace -a :"
  image: "registry.gitlab.com/3_1_3_u/cloud9-sdk:latest"
  restart: "always"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/usr/local/bin/docker:/bin/docker"
    - "./myworkspace:/workspace"
